import { PresetTarget, StepLog, IntelligenceMetric, QuestionHook, DetectedTech, ProspectLead, PlatformFeature } from '@/types';

export const PRESET_TARGETS: PresetTarget[] = [
  {
    id: '1',
    name: 'Stripe',
    domain: 'stripe.com',
    category: 'Fintech & Payments',
    logo: '💳',
    description: 'Financial infrastructure for the internet powering millions of businesses worldwide.',
    icpScore: 96,
  },
  {
    id: '2',
    name: 'Linear',
    domain: 'linear.app',
    category: 'Developer Tools & SaaS',
    logo: '⚡',
    description: 'Purpose-built tool for modern software development, issue tracking and roadmaps.',
    icpScore: 92,
  },
  {
    id: '3',
    name: 'Vercel',
    domain: 'vercel.com',
    category: 'Cloud Platform',
    logo: '▲',
    description: 'Frontend cloud platform enabling developer teams to deploy instant web applications.',
    icpScore: 95,
  },
  {
    id: '4',
    name: 'HubSpot',
    domain: 'hubspot.com',
    category: 'CRM & Marketing Automation',
    logo: '🧡',
    description: 'Customer platform delivering marketing, sales, and customer service software.',
    icpScore: 88,
  },
];

export const MOCK_LOADING_STEPS: StepLog[] = [
  {
    id: 's1',
    stepName: 'DNS & Domain Metadata Extraction',
    status: 'completed',
    detail: 'Extracted SSL certificate, hosting headers, MX records, and subdomain infrastructure.',
    duration: '0.4s',
    timestamp: '12:04:01',
  },
  {
    id: 's2',
    stepName: 'Technology Stack Detection',
    status: 'completed',
    detail: 'Identified React 19, Next.js, Tailwind CSS, Segment, Google Tag Manager, and Stripe Billing SDK.',
    duration: '1.2s',
    timestamp: '12:04:03',
  },
  {
    id: 's3',
    stepName: 'Executive Team & Contact Mining',
    status: 'completed',
    detail: 'Crawled public signals for VP Sales, Head of Growth, and CTO email schemas.',
    duration: '1.8s',
    timestamp: '12:04:05',
  },
  {
    id: 's4',
    stepName: 'Sales Objection & Intent Synthesis',
    status: 'in_progress',
    detail: 'Analyzing recent news triggers, job postings, and key selling hooks using AI synthesis algorithms.',
    duration: 'Running...',
    timestamp: '12:04:07',
  },
  {
    id: 's5',
    stepName: 'ICP Score & Playbook Generation',
    status: 'pending',
    detail: 'Compiling final executive summary, discovery question matrix, and export payload.',
    timestamp: 'Pending',
  },
];

export const MOCK_INTELLIGENCE_METRICS: IntelligenceMetric[] = [
  {
    title: 'ICP Compatibility Score',
    value: '94 / 100',
    change: '+8% vs Industry Avg',
    changeType: 'positive',
    description: 'Extremely high match based on stack tech, team size, and growth signals.',
    iconName: 'Target',
  },
  {
    title: 'Est. Annual Revenue',
    value: '$25M - $50M',
    change: 'Series C Funded',
    changeType: 'positive',
    description: 'SaaS ARR trajectory calculated from hiring velocity and employee count.',
    iconName: 'DollarSign',
  },
  {
    title: 'Tech Stack Density',
    value: '28 Technologies',
    change: 'Modern Stack',
    changeType: 'positive',
    description: 'High software expenditure with modern developer & marketing tools.',
    iconName: 'Cpu',
  },
  {
    title: 'Buying Intent Signals',
    value: 'High Intent',
    change: '3 Triggers Active',
    changeType: 'positive',
    description: 'Actively hiring 12+ engineers and expanding outbound sales team.',
    iconName: 'TrendingUp',
  },
];

export const MOCK_SALES_QUESTIONS: QuestionHook[] = [
  {
    id: 'q1',
    category: 'Pain Point',
    question: 'How are you currently handling sales data enrichment across disparate CRM platforms without manual data entry?',
    context: 'Target company recently posted 4 job listings for Sales Operations Managers emphasizing manual lead cleanup.',
    confidenceScore: 95,
  },
  {
    id: 'q2',
    category: 'Value Proposition',
    question: 'Our automator reduces prospect research time from 45 minutes down to 3 seconds, delivering actionable discovery hooks straight to your SDRs.',
    context: 'Direct alignment with their high-velocity outbound Motion.',
    confidenceScore: 92,
  },
  {
    id: 'q3',
    category: 'Qualifying Question',
    question: 'What percentage of your outbound outbound emails receive responses based on customized technical insights?',
    context: 'Identified legacy outreach tool usage that lacks tech stack detection.',
    confidenceScore: 89,
  },
  {
    id: 'q4',
    category: 'Objection Handler',
    question: '"We already use ZoomInfo / Apollo" → Show our real-time intent signal detection & sales question generation that legacy databases do not offer.',
    context: 'Prevents standard vendor lock-in objections.',
    confidenceScore: 94,
  },
];

export const MOCK_DETECTED_TECH: DetectedTech[] = [
  { name: 'Next.js 15', category: 'Frontend Framework' },
  { name: 'Tailwind CSS', category: 'Styling & UI' },
  { name: 'Stripe API', category: 'Payment Infrastructure' },
  { name: 'Segment.io', category: 'Customer Data Platform' },
  { name: 'HubSpot Marketing', category: 'Marketing Automation' },
  { name: 'AWS CloudFront', category: 'CDN & Hosting' },
  { name: 'PostgreSQL', category: 'Database Engine' },
  { name: 'Mixpanel', category: 'Product Analytics' },
];

export const MOCK_LEADS: ProspectLead[] = [
  {
    id: 'l1',
    name: 'Sarah Jenkins',
    title: 'VP of Global Sales Operations',
    company: 'CloudScale Technologies',
    domain: 'cloudscale.io',
    email: 's.jenkins@cloudscale.io',
    phone: '+1 (555) 234-8901',
    location: 'San Francisco, CA',
    icpScore: 98,
    status: 'Hot Lead',
    techStack: ['Salesforce', 'HubSpot', 'Segment'],
    lastActivity: '2 mins ago',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  {
    id: 'l2',
    name: 'Marcus Vance',
    title: 'Head of Outbound Demand Generation',
    company: 'Apex Data Labs',
    domain: 'apexdatalabs.com',
    email: 'marcus@apexdatalabs.com',
    phone: '+1 (555) 456-1122',
    location: 'New York, NY',
    icpScore: 94,
    status: 'Verified',
    techStack: ['Marketo', 'Outreach', 'Snowflake'],
    lastActivity: '1 hour ago',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'l3',
    name: 'Elena Rostova',
    title: 'Chief Revenue Officer (CRO)',
    company: 'FinFlow Global',
    domain: 'finflow.app',
    email: 'elena@finflow.app',
    phone: '+1 (555) 987-6543',
    location: 'Austin, TX',
    icpScore: 91,
    status: 'Enriched',
    techStack: ['Stripe', 'Intercom', 'Next.js'],
    lastActivity: '3 hours ago',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    id: 'l4',
    name: 'David Chen',
    title: 'Director of Business Development',
    company: 'HyperPulse Security',
    domain: 'hyperpulse.sec',
    email: 'dchen@hyperpulse.sec',
    phone: '+1 (555) 321-7788',
    location: 'Seattle, WA',
    icpScore: 87,
    status: 'Contacted',
    techStack: ['AWS', 'HubSpot', 'Datadog'],
    lastActivity: 'Yesterday',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'l5',
    name: 'Jessica Taylor',
    title: 'Senior Manager, Sales Strategy',
    company: 'OmniGrowth Inc',
    domain: 'omnigrowth.co',
    email: 'j.taylor@omnigrowth.co',
    phone: '+1 (555) 888-4411',
    location: 'Chicago, IL',
    icpScore: 85,
    status: 'Verified',
    techStack: ['Gainsight', 'Salesforce', 'Zendesk'],
    lastActivity: '2 days ago',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
  },
];

export const MOCK_FEATURES: PlatformFeature[] = [
  {
    id: 'f1',
    title: 'Automated Account Intelligence',
    description: 'Extract technical signals, domain DNS, traffic data, and employee count in seconds without manual web scraping.',
    icon: 'Search',
    tag: 'Core Signal Engine',
    benefits: ['Sub-second scan times', '99.8% data accuracy', 'DNS & tech fingerprinting'],
  },
  {
    id: 'f2',
    title: 'Sales Playbook & Pitch Generator',
    description: 'Automatically generate high-converting discovery questions, personalized hooks, and objection handlers tailored to target tech stacks.',
    icon: 'Sparkles',
    tag: 'AI Playbook Generator',
    benefits: ['Tailored pain point prompts', 'Direct objection matrix', 'Instant SDR cheat sheet'],
  },
  {
    id: 'f3',
    title: 'ICP Matching & Intent Scoring',
    description: 'Score prospects against your ideal customer profile with customizable criteria and buying trigger detection.',
    icon: 'Target',
    tag: 'Smart Qualification',
    benefits: ['Dynamic score 0-100', 'Buying trigger alerts', 'Custom qualification rules'],
  },
  {
    id: 'f4',
    title: 'High-Density Prospect Management',
    description: 'Organize enriched leads with instant table view, tag filtering, verified contacts, and multi-format export options.',
    icon: 'Users',
    tag: 'Lead Directory',
    benefits: ['Verified email detection', 'CSV & JSON exporting', 'Filterable tags & roles'],
  },
];
